---
title: "Git notes again"
format: html
---

## Basics of using git

Git is a distributed version control system (VCS) that is very popular.

The core steps to using git involve

1. Initiate a git repository
    In RStudio we just clikc a little radio button on project creation
    At the command line we type:
    `git init`
    
2. Do your normal work
    Add files
    Modify files etc.
    
3. Add your important files to the "stage
    In RStudio we click "staged" radio button
    `git add yourfilename`

4. Commit your staged files to the repository
    In RStudio you just hit the "Commit" button and add a msg
    `git commit -m "your wee msg"`

5. Git Push to sync changes T0 GitHub
    In RStudio you just hit the "Push" button
    `git push` (you may need to set up a remote repo first)

6. Git Pull to sync changes from GitHub to your local repo
    In RStudio you just hit the "Pull" button
    `git pull` (you may need to set up a remote repo first)

You can check your project "history" and status
    `git status`
    `git log`  (push Q to exi)







